# Generated by Django 5.0.6 on 2024-06-13 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuation_questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiongroup",
            name="text",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
