# Generated by Django 5.0.6 on 2024-06-13 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuation_questions", "0002_questiongroup_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_group",
        ),
        migrations.AddField(
            model_name="question",
            name="group",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="valuation_questions.questiongroup",
            ),
            preserve_default=False,
        ),
    ]
