# Generated by Django 5.0.6 on 2024-05-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_questions', '0003_remove_option_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='selections',
            new_name='selected',
        ),
    ]
