# Generated by Django 5.0.6 on 2024-06-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "valuation_questions",
            "0002_remove_question_pub_date_question_created_at_and_more",
        ),
        (
            "valuation_questions",
            "0003_remove_question_group_remove_question_pub_date_and_more",
        ),
        ("valuation_questions", "0003_remove_question_question_group_question_group"),
    ]

    operations = []
